version: "3.8"

services:
    core:
        build:
            context: ./
            dockerfile: Dockerfile
        tty: true
        ports:
            - 4000:4000
        volumes:
            - ./:/project
        command: /bin/bash -c "bundle check || bundle install"