version: "3.8"

services:
    temp_container:
        build:
            context: ./
            dockerfile: ./Dockerfile
        volumes:
          - .:/app
        environment:
          - TOKEN=${TOKEN}
        command: >
          /bin/bash -c "git config --global --add safe.directory /app &&
          cd /app &&
          bundle install &&
          rm -rf _articles docs || true
          mkdir -p _articles &&
          mkdir -p docs &&
          python generate_html.py &&
          bundle exec jekyll build --incremental &&
          pagefind --site docs"
