version: "3.8"

services:
    temp_container:
        image: myapp-app-cached
        build:
            context: ./
            dockerfile: ./Dockerfile
        volumes:
          - .:/app
        environment:
          - TOKEN=${TOKEN}
        command: >
          /bin/bash -c "cd /app && 
          bundle install &&
          python generate_html.py &&
          bundle exec jekyll build"
