name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'  # 毎日0時に実行
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v4

    - name: Configure GitHub Pages
      uses: actions/configure-pages@v5

    - name: docker compose build & up
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        docker compose -f docker-compose.deploy.yaml build --pull --no-cache
        docker compose -f docker-compose.deploy.yaml up --abort-on-container-exit --exit-code-from temp_container

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: ./docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
