name: Issue Correction

on:
  issues:
    types: [opened, labeled]

jobs:
  correct_issue_title:
    runs-on: ubuntu-latest
    if: github.actor == 'AkihikoWatanabe'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install PyGithub feedparser openai==1.55.3
    - name: Correct Issue
      env:
        TOKEN: ${{ secrets.TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python .github/scripts/correct_issue.py
